make_fsl common\compile.so common\compile.fsl
make_fsl common\memory.so common\memory.fsl
make_fsl common\clisp.so common\clisp.fsl
make_fsl common\reducer.so common\reducer.fsl
make_fsl windows\interface.so windows\interface.fsl
make_fsl common\tests.so common\tests.fsl
make_fsl windows\textwin.so windows\textwin.fsl
make_fsl windows\scrollwin.so windows\scrollwin.fsl
make_fsl windows\valuewin.so windows\valuewin.fsl

