(load "c:\\scheme\\scoops.fsl")
(load "common\\clisp.fsl")
(load "windows\\textwin.fsl")
(load "windows\\scrollwi.fsl")
(load "windows\\valuewin.fsl")
(load "common\\memory.fsl")
(load "common\\compile.fsl")
(load "common\\reducer.fsl")
(load "windows\\interface.fsl")
(load "common\\tests.fsl")
(load "instructions.s")
(load "primitive.s")
;(load "equal.s")
(load "unify.s")

(set! pcs-debug-mode #T)



(define (compile-red)
	(set! pcs-debug-mode #F)
	(compile-file "common\\clisp.s" "common\\clisp.so")
	(compile-file "windows\\textwin.s" "windows\\textwin.so")
	(compile-file "windows\\scrollwi.s" "windows\\scrollwin.so")
	(compile-file "windows\\valuewin.s" "windows\\valuewin.so")
	(compile-file "common\\memory.s" "common\\memory.so")
	(compile-file "common\\compile.s" "common\\compile.so")
	(compile-file "common\\reducer.s" "common\\reducer.so")
	(compile-file "windows\\interface.s" "windows\\interface.so")
	(compile-file "common\\tests.s" "common\\tests.so")
)
