# Huge memory model
MODEL=H

# compiler flags
CFLAGS=/A$(MODEL) /c  /Ox /DIBM

CL=cl $(CFLAGS)

.C.OBJ: 
      $(CL) $*.C

.Y.C:
	 pcyacc $*.Y


compiler.c: compiler.y

main.obj: main.c lrs.h

red.obj: red.c lrs.h

prims.obj: prims.c lrs.h

arith.obj: arith.c lrs.h

compiler.obj: compiler.c lrs.h

edit.obj: edit.c 

debug.obj: debug.c lrs.h

printer.obj: printer.c lrs.h
	cl /AH /c /DIBM printer.c

# make the executable

horse.exe: main.obj red.obj prims.obj arith.obj compiler.obj printer.obj \
		 edit.obj debug.obj 
     LINK $**, $@, NUL.MAP, lcurses.lib 

